ABSTRACTION  :   HIDING THE IMPLEMENTATION DETAILS AND SHOWING ONLY FUNCTIONS and implented by child class
FOR EXAMPLE VEHICLE IS SUPER CLASS && BOAR,CAR,BICYCLE ARE CHILD CLASSES
            CAR ONLY CAN SAY THAT IT BELONGS TO WHICH COMPANY BUT VEHICLE CANNOT....
            THIS FUNCTION IS CALLED ABSTRACTION

*****IF THERE IS ABSTRACT IN IN CLASS....THAT CLASS SHOULD BE ABSTRACT TOO****

\\\\\SUPER CLASS
public abstract class vehicle()
{
string name;
int speed;

public void abstract isMotorized()
{
return false;
}
}
\\\\\CHILD CLASS






INTERFACEC: EXTENSION OF ABSTRACTC CLASS

***MULTIPLE INTERFACE CAN BE IMPLENTED BY ONE CLASS
ONE CLASS CANNOT EXTEND SEVERAL CLASSES
